apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-nodejs-using_cloudevents_with_knative
  title: CloudEvents with Node.js
  description: |
    Building a CloudEvents Transaction Chain with Node.js
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - cloudevents
    - serverless
    - kafka
    - nodejs
# links:
#    - url: https://<openshift-cluster>/#<hosted-git-repo>
#      title: "Launch from Dev Spaces"
#      icon: web
spec:
  type: module
  lifecycle: production
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
