site_name: CloudEvents with Node.js
site_description: Building a CloudEvents Transaction Chain with Node.js

nav:
  - Overview: index.md
  - CloudEvents Workflow: cloudevents-workflow.md
  - How It Works: how-it-works.md

plugins:
  - techdocs-core
